---
# tasks file for nginx-service

- name: EPEL Repository Install
  yum:
   name: epel-release
   state: present

- name: Nginx Install
  yum:
    name: nginx
    state: present

- naem: Nginx Service Start
  service:
    name: nginx
    state: started
    enabled: true

