---
# tasks file for nginx-service

- name: EPEL Repository Install
  yum_repository:
   name: epel
   description: EPEL YUM repo
   baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: Nginx Install
  yum:
    name: nginx
    state: present

- naem: Nginx Service Start
  service:
    name: nginx
    state: started
    enabled: true

